/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ContactMe: typeof import('./src/components/ContactMe.vue')['default']
    FirstVisitWelcome: typeof import('./src/components/FirstVisitWelcome.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    MenuView: typeof import('./src/components/MenuView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
